{% set name = "hart-protocol" %}
{% set version = "2022.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hart-protocol-{{ version }}.tar.gz
  sha256: 5032617861f6a49397919b4dd6b9f0d0ef3a5ffb43ca752c0e2277eefd592759

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core
  run:
    - python >=3.7

test:
  imports:
    - hart_protocol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yaq-project/hart-protocol
  summary: A sans-io python implementation of the Highway Addressable Remote Transducer Protocol.
  dev_url: https://github.com/yaq-project/hart-protocol
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - untzag
